# Generated by Django 4.2.5 on 2023-10-03 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('paste_data', models.FileField(upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('paste_digest', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
