# Generated by Django 4.2.5 on 2023-10-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='paste_data',
        ),
        migrations.AddField(
            model_name='paste',
            name='paste_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
