# Generated by Django 4.2.5 on 2023-10-04 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tbin', '0002_remove_paste_paste_data_paste_paste_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='short_id',
            field=models.CharField(default=123, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paste',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paste',
            name='paste_digest',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
