# Generated by Django 4.2.5 on 2023-10-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbin', '0004_user_alter_paste_paste_digest_paste_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='acceptable_viewer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='tbin.user'),
        ),
        migrations.AddField(
            model_name='paste',
            name='view_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paste',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tbin.user'),
        ),
    ]
