# Generated by Django 4.2.5 on 2023-10-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbin', '0005_paste_acceptable_viewer_paste_view_limited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='acceptable_viewer',
        ),
        migrations.AlterField(
            model_name='paste',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_paste', to='tbin.user'),
        ),
        migrations.AddField(
            model_name='paste',
            name='acceptable_viewer',
            field=models.ManyToManyField(default=None, related_name='accessable_paste', to='tbin.user'),
        ),
    ]
