# Generated by Django 4.2.5 on 2023-10-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbin', '0006_remove_paste_acceptable_viewer_alter_paste_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='acceptable_viewer',
            field=models.ManyToManyField(blank=True, default=None, related_name='accessable_paste', to='tbin.user'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_paste', to='tbin.user'),
        ),
    ]
