# Generated by Django 4.2.5 on 2023-10-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbin', '0007_alter_paste_acceptable_viewer_alter_paste_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
